create table "public"."first_table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."first_table" enable row level security;

create table "public"."fourth_table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."fourth_table" enable row level security;

create table "public"."second_table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."second_table" enable row level security;

create table "public"."third_table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."third_table" enable row level security;

CREATE UNIQUE INDEX first_table_pkey ON public.first_table USING btree (id);

CREATE UNIQUE INDEX fourth_table_pkey ON public.fourth_table USING btree (id);

CREATE UNIQUE INDEX second_table_pkey ON public.second_table USING btree (id);

CREATE UNIQUE INDEX third_table_pkey ON public.third_table USING btree (id);

alter table "public"."first_table" add constraint "first_table_pkey" PRIMARY KEY using index "first_table_pkey";

alter table "public"."fourth_table" add constraint "fourth_table_pkey" PRIMARY KEY using index "fourth_table_pkey";

alter table "public"."second_table" add constraint "second_table_pkey" PRIMARY KEY using index "second_table_pkey";

alter table "public"."third_table" add constraint "third_table_pkey" PRIMARY KEY using index "third_table_pkey";

grant delete on table "public"."first_table" to "anon";

grant insert on table "public"."first_table" to "anon";

grant references on table "public"."first_table" to "anon";

grant select on table "public"."first_table" to "anon";

grant trigger on table "public"."first_table" to "anon";

grant truncate on table "public"."first_table" to "anon";

grant update on table "public"."first_table" to "anon";

grant delete on table "public"."first_table" to "authenticated";

grant insert on table "public"."first_table" to "authenticated";

grant references on table "public"."first_table" to "authenticated";

grant select on table "public"."first_table" to "authenticated";

grant trigger on table "public"."first_table" to "authenticated";

grant truncate on table "public"."first_table" to "authenticated";

grant update on table "public"."first_table" to "authenticated";

grant delete on table "public"."first_table" to "service_role";

grant insert on table "public"."first_table" to "service_role";

grant references on table "public"."first_table" to "service_role";

grant select on table "public"."first_table" to "service_role";

grant trigger on table "public"."first_table" to "service_role";

grant truncate on table "public"."first_table" to "service_role";

grant update on table "public"."first_table" to "service_role";

grant delete on table "public"."fourth_table" to "anon";

grant insert on table "public"."fourth_table" to "anon";

grant references on table "public"."fourth_table" to "anon";

grant select on table "public"."fourth_table" to "anon";

grant trigger on table "public"."fourth_table" to "anon";

grant truncate on table "public"."fourth_table" to "anon";

grant update on table "public"."fourth_table" to "anon";

grant delete on table "public"."fourth_table" to "authenticated";

grant insert on table "public"."fourth_table" to "authenticated";

grant references on table "public"."fourth_table" to "authenticated";

grant select on table "public"."fourth_table" to "authenticated";

grant trigger on table "public"."fourth_table" to "authenticated";

grant truncate on table "public"."fourth_table" to "authenticated";

grant update on table "public"."fourth_table" to "authenticated";

grant delete on table "public"."fourth_table" to "service_role";

grant insert on table "public"."fourth_table" to "service_role";

grant references on table "public"."fourth_table" to "service_role";

grant select on table "public"."fourth_table" to "service_role";

grant trigger on table "public"."fourth_table" to "service_role";

grant truncate on table "public"."fourth_table" to "service_role";

grant update on table "public"."fourth_table" to "service_role";

grant delete on table "public"."second_table" to "anon";

grant insert on table "public"."second_table" to "anon";

grant references on table "public"."second_table" to "anon";

grant select on table "public"."second_table" to "anon";

grant trigger on table "public"."second_table" to "anon";

grant truncate on table "public"."second_table" to "anon";

grant update on table "public"."second_table" to "anon";

grant delete on table "public"."second_table" to "authenticated";

grant insert on table "public"."second_table" to "authenticated";

grant references on table "public"."second_table" to "authenticated";

grant select on table "public"."second_table" to "authenticated";

grant trigger on table "public"."second_table" to "authenticated";

grant truncate on table "public"."second_table" to "authenticated";

grant update on table "public"."second_table" to "authenticated";

grant delete on table "public"."second_table" to "service_role";

grant insert on table "public"."second_table" to "service_role";

grant references on table "public"."second_table" to "service_role";

grant select on table "public"."second_table" to "service_role";

grant trigger on table "public"."second_table" to "service_role";

grant truncate on table "public"."second_table" to "service_role";

grant update on table "public"."second_table" to "service_role";

grant delete on table "public"."third_table" to "anon";

grant insert on table "public"."third_table" to "anon";

grant references on table "public"."third_table" to "anon";

grant select on table "public"."third_table" to "anon";

grant trigger on table "public"."third_table" to "anon";

grant truncate on table "public"."third_table" to "anon";

grant update on table "public"."third_table" to "anon";

grant delete on table "public"."third_table" to "authenticated";

grant insert on table "public"."third_table" to "authenticated";

grant references on table "public"."third_table" to "authenticated";

grant select on table "public"."third_table" to "authenticated";

grant trigger on table "public"."third_table" to "authenticated";

grant truncate on table "public"."third_table" to "authenticated";

grant update on table "public"."third_table" to "authenticated";

grant delete on table "public"."third_table" to "service_role";

grant insert on table "public"."third_table" to "service_role";

grant references on table "public"."third_table" to "service_role";

grant select on table "public"."third_table" to "service_role";

grant trigger on table "public"."third_table" to "service_role";

grant truncate on table "public"."third_table" to "service_role";

grant update on table "public"."third_table" to "service_role";

create policy "Enable select for authenticated users only"
on "public"."first_table"
as permissive
for select
to authenticated
using (true);

create policy "Enable select for authenticated users only"
on "public"."second_table"
as permissive
for select
to authenticated
using (true);

create policy "Enable select for authenticated users only"
on "public"."third_table"
as permissive
for select
to authenticated
using (true);

create policy "Enable select for authenticated users only"
on "public"."fourth_table"
as permissive
for select
to authenticated
using (true);











